Repository dalagnol/feathery-frontend, pull requests merged in 2019-12, with the labels that each got.

#3 packages installed
  package.json
  yarn.lock
Labels: good first issue

#9 Update README.md
  README.md
Labels: documentation

#11 Setup/implement architecture
  .env
  .eslintrc
  .prettierrc
  package.json
  src/App.css
  src/App.js
  src/App.test.js
  src/app/App.test.ts
  src/app/App.tsx
  src/app/index.ts
  src/app/styles.ts
  src/assets/index.ts
  src/components/index.ts
  src/index.css
  src/index.js
  src/index.tsx
  src/interfaces/Redux.ts
  src/locale/index.ts
  src/logo.svg
  src/react-app-env.d.ts
  src/routes/admins.test.tsx
  src/routes/admins.tsx
  src/routes/commons.test.tsx
  src/routes/commons.tsx
  src/routes/index.ts
  src/routes/public.test.tsx
  src/routes/public.tsx
  src/serviceWorker.js
  src/services/api.ts
  src/services/index.ts
  src/setupTests.js
  src/shared/index.ts
  src/store/ducks/index.ts
  src/store/ducks/user.ts
  src/store/index.ts
  src/styles/index.ts
  src/tests/index.ts
  src/views/index.ts
  src/views/setupTests.ts
  tsconfig.json
  yarn.lock
Labels: enhancement
